"""category-type

Revision ID: 05eb5bea8fb0
Revises: 8da0f475c875
Create Date: 2025-04-22 00:00:57.330986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05eb5bea8fb0'
down_revision: Union[str, None] = '8da0f475c875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categories', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Categories', 'type')
    # ### end Alembic commands ###